-- Replace the permissive module policy with server-enforced module roles.
-- Apply after 008_expenses_permissions.sql; expense policies are intentionally untouched.
BEGIN;

DO $$
DECLARE
  item record;
BEGIN
  FOR item IN
    SELECT * FROM (VALUES
      ('calendar_events', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT','FINANCE','CAISSIER','CANTINE_TRANSPORT','RESP_CANTINE','RESP_TRANSPORT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT']),
      ('decision_rules', ARRAY['ADMIN_GENERALE','DIRECTEUR'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('subject_categories', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('subjects', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('subject_components', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('level_subjects', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('assessment_sessions', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT']),
      ('assessment_results', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT']),
      ('assessment_scores', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT']),
      ('parents', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT','FINANCE','CAISSIER'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('medical_records', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('student_attendance', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT']),
      ('student_documents', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('student_status_history', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('staff', ARRAY['ADMIN_GENERALE','DIRECTEUR'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('staff_members', ARRAY['ADMIN_GENERALE','DIRECTEUR'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('staff_departments', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('staff_positions', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('staff_contracts', ARRAY['ADMIN_GENERALE','DIRECTEUR'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('staff_documents', ARRAY['ADMIN_GENERALE','DIRECTEUR'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('transport_vehicles', ARRAY['ADMIN_GENERALE','DIRECTEUR','CANTINE_TRANSPORT','RESP_TRANSPORT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','CANTINE_TRANSPORT','RESP_TRANSPORT']),
      ('transport_drivers', ARRAY['ADMIN_GENERALE','DIRECTEUR','CANTINE_TRANSPORT','RESP_TRANSPORT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','CANTINE_TRANSPORT','RESP_TRANSPORT']),
      ('fee_configs', ARRAY['ADMIN_GENERALE','DIRECTEUR','FINANCE','CAISSIER'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('fee_records', ARRAY['ADMIN_GENERALE','DIRECTEUR','FINANCE','CAISSIER'], ARRAY['ADMIN_GENERALE','DIRECTEUR','FINANCE','CAISSIER']),
      ('school_fees', ARRAY['ADMIN_GENERALE','DIRECTEUR','FINANCE','CAISSIER'], ARRAY['ADMIN_GENERALE','DIRECTEUR','FINANCE','CAISSIER']),
      ('history_logs', ARRAY['ADMIN_GENERALE','DIRECTEUR'], ARRAY['ADMIN_GENERALE','DIRECTEUR']),
      ('document_blocks', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('document_templates', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('template_blocks', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE']),
      ('generated_documents', ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE','SCOLAIRE_ENSEIGNANT','ENSEIGNANT'], ARRAY['ADMIN_GENERALE','DIRECTEUR','SECRETAIRE'])
    ) AS permissions(table_name, read_roles, write_roles)
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS module_read ON public.%I', item.table_name);
    EXECUTE format('DROP POLICY IF EXISTS module_write ON public.%I', item.table_name);
    EXECUTE format('CREATE POLICY module_read ON public.%I FOR SELECT TO authenticated USING (public.gesco_role() = ANY(%L::text[]))', item.table_name, item.read_roles);
    EXECUTE format('CREATE POLICY module_insert ON public.%I FOR INSERT TO authenticated WITH CHECK (public.gesco_role() = ANY(%L::text[]))', item.table_name, item.write_roles);
    EXECUTE format('CREATE POLICY module_update ON public.%I FOR UPDATE TO authenticated USING (public.gesco_role() = ANY(%L::text[])) WITH CHECK (public.gesco_role() = ANY(%L::text[]))', item.table_name, item.write_roles, item.write_roles);
    EXECUTE format('CREATE POLICY module_delete ON public.%I FOR DELETE TO authenticated USING (public.gesco_role() IN (''ADMIN_GENERALE'', ''DIRECTEUR''))', item.table_name);
  END LOOP;
END $$;

COMMIT;
